### ISSUE TITLE
BatchEventRestModelCreator constructor should take in a Long object

### ISSUE THREAD

**Issue by menardsmobileapp** [qubitdigital/qubit-sdk-android#3]
The class has a Long object, but the constructor takes in a long primitive. If null is attempted to be passed in, (which is possible since the forBatch() also takes in a Long object), then it will crash.

`private final Long batchTimestamp;
    private final Integer timezoneOffsetMins;
    private final EventTypeTransformer eventTypeTransformer;
    private final LookupData lookupData;

    private BatchEventRestModelCreator(long batchTimestamp, Integer timezoneOffsetMins,
                                       EventTypeTransformer eventTypeTransformer, LookupData lookupData) {
      this.batchTimestamp = batchTimestamp;
      this.timezoneOffsetMins = timezoneOffsetMins;
      this.eventTypeTransformer = eventTypeTransformer;
      this.lookupData = lookupData;
    }`

**Comment by DominikJura** [comment]
Hi thanks for pointing that @menardsmobileapp, it will be handle in version 1.3.0 version
